### ISSUE TITLE
Is there any particular reason why jira url isn't configurable?

### ISSUE THREAD

**Issue by IvanAnishchuk** [msolomonTMG/timesheet-githook#2]
It could've been set in the credentials file, for example, and configured on the first run.

**Comment by msolomonTMG** [comment]
@IvanAnishchuk  - No good reason... I initially just set this hook up for my team and I wanted to make it as frictionless as possible for them to start using it. If someone sends me a smooth way to configure the URL, I'd merge that PR for sure!
